### ISSUE TITLE
Drupal 9

### ISSUE THREAD

**Issue by jsibley2** [xenomedia/xeno_hero#26]
Will there be an update for Drupal 9?

Also, in the meantime, how do I remove this from Drupal 8? If I use composer remove, I get an error when running drush updatedb that the file does not exist "in assert() (line 67 of /app/docroot/core/lib/Drupal/Core/Extension/Extension.php)."

**Comment by albertski** [comment]
I believe it may already work with Drupal 9. I'm not sure what the error is you are getting. Perhaps you didn't uninstall the module first.

**Comment by Elvin-Xhimitiku** [comment]
good job with the module alberski! do you have plans on pushing this to drupal.org?

**Comment by albertski** [comment]
@Elvin-Xhimitiku,
Sorry, for the delay. I added to my list to push this to drupal.org.
