### ISSUE TITLE
Not able to get the content on overlays

### ISSUE THREAD

**Issue by preritmohan** [xenomedia/xeno_hero#5]

**Comment by thejimbirch** [comment]
Please provide more information.

**Comment by preritmohan** [comment]
Hi Jim, So here is what I did. I Installed "bootstrap paragraphs" , "paragraphs" and xeno_hero module. After that I added paragraphs "entity reference" to my custom content type.

Now when I create the paragraph of any type say "Simple" or "Xeno Hero" the color and width classes are not being added the wrapping div instead they are dumped on the screen itself. Same with Xeno Hero. I only get a full image with title and other settings at the bottom on the paragraphs. More info here https://drupal.stackexchange.com/questions/235479/drupal-8-bootstrap-paragraphs-not-rendering-color-and-width-classes

Am I missing any config? Attaching xeno hero implementation screenshot.

![xeno hero](https://cloud.githubusercontent.com/assets/1901400/25680257/2a79887e-301e-11e7-8372-a071554d380f.PNG)


Thanks

**Comment by thejimbirch** [comment]
I asked some questions at: https://drupal.stackexchange.com/questions/235479/drupal-8-bootstrap-paragraphs-not-rendering-color-and-width-classes

**Comment by preritmohan** [comment]
Please check my response on the stackexchange.

**Comment by preritmohan** [comment]
Works after disabling "Field Layout" and "Layout Discovery" which in turn are required by "DS and Bootstrap Layouts". What are your thoughts on this. Is it overriding templates?

**Comment by thejimbirch** [comment]
From your screenshots, it looks like it is adding template suggestions back in for the width and color fields.  That makes it ignore what we are specifying in the Paragraphs bundle level templates, to print the content without those two fields.

**Comment by preritmohan** [comment]
Understood. Thanks for the help. Appreciate it.
