### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by MrPaulDriver** [xenomedia/xeno_hero#7]
Drupal 8. I'm new to paragraphs so not sure if i'm doing this properly. I am not using Bootstrap but understand this is not a dependancy for this module. (??)

1. Installed paragraphs module, entity_revisions and xeno_hero
2. Added paragraph field to custom block (also to a content type)
3. When trying to create a custom block (or new content) I get a long delay, followed by an out of memory error, as below;

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 200704 bytes) in /Users/paul/Google Drive/EASABLE/SITES/drupal8composer/web/modules/contrib/paragraphs/src/Plugin/Field/FieldWidget/InlineParagraphsWidget.php on line 347

Be interested to know if I am doing something wrong?

**Comment by thejimbirch** [comment]
Hi,

Not exactly sure, I've never run into it before.  Sounds like a server/PHP error.

Googling led me to this:

https://www.drupal.org/node/2868155

Try installing the dev version of Paragraphs.

Good Luck,
Jim
